name: Kwiki-Soap-Google
version: 0.03
abstract: Access Google SOAP services from kwiki wafl phrase
author: Chris Dent <cdent@burningchrome.com>
license: perl
distribution_type: module
requires:
  Kwiki::SOAP: 0
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
